### ISSUE TITLE
Avoiding daemonic force_taints

### ISSUE THREAD

**Issue by LordNoxington** [abunai10/CaffeineIssues#16]
Not sure if there is another method for unlocking these, other than annoying you guys to do it <3

SpellStopCasting()
SecureCmdItemParse()
SecureCmdUseItem()
SecureCmdOptionParse()
ClearFocus()
CancelSpellByName()
UseInventoryItem()
SpellCancelQueuedSpell()
CastSpellByID()
DeleteCursorItem()
ClearCursor()
GetItemInfo()
CastSpellByName()

**Comment by LordNoxington** [comment]
UPDATE:
Click()
PetAttack()
PetFollow()
PetStopAttack()
TargetUnit()
StartAttack()
FocusUnit()
IsUsableItem()

**Comment by n00bsteam** [comment]
One more:
C_QuestLog.UnitIsRelatedToActiveQuest()

**Comment by abunai10** [comment]
Added:
SecureCmdOptionParse
PetFollow
PetStopAttack
FocusUnit
C_QuestLog.UnitIsRelatedToActiveQuest

The rest either are already unlocked or do not need to be unlocked. Please check that we haven't already unlocked functions before requesting them in the future.
