### ISSUE TITLE
GetCastLength() returns also Range, Spell ID and wrong Formatted Time.

### ISSUE THREAD

**Issue by denisdasilvarocha** [abunai10/CaffeineIssues#17]
Hey There!

GetCastLength() returns stuff we dont actually need and also the SpellCastTime is wrong formatted.
Atleast in Wrath, Retail i dont know.

![Screenshot 2023-11-08 at 10 31 47](https://github.com/abunai10/CaffeineIssues/assets/92863811/faed82cb-8b9b-4519-8e46-27752a1e89a9)

## Issue

```lua
Caffeine:Print(spells.vampiricTouch:GetCastLength())
```

## Returns
[Caffeine] 1421 0 36 48160 

|SpellCastTime|GCD?|Spell Range|Spell ID|              
|---------------|----|-----------|--------|
|`1421`             |`0`  | `36`         |48160

## Task
Please refactor the GetCastLength() function, so it does only return the SpellCastTime of the givin Spell.
Something like this.

```lua 
function Spell:GetCastLength()
    local castTime = select(4, GetSpellInfo(self:GetID()))
    return castTime / 1000  -- convert to seconds
end
```

**Comment by abunai10** [comment]
Should be fixed on next update.
