### ISSUE TITLE
Polyfill for ObjectCastingTarget

### ISSUE THREAD

**Issue by n00bsteam** [abunai10/CaffeineIssues#19]
Add support ObjectCastingTarget for Daemonic unlocker.

At the moment we have got no other ways to detect Unit casting target, workaround like:
```lua
Caffeine.UnitManager:EnumEnemies(function(unit)
  if unit:IsCastingOrChanneling() then
    print(unit:GetTarget())
  end
end)
```

returns false for Tinkr and Daemonic.

Can be tested at Valdrakken Tank Dummy

**Comment by JustRebeccabla** [comment]
UnitCastingTarget is the api on Daemonic. 🆗

**Comment by LordNoxington** [comment]
Works perfect now

**Comment by Laksmack** [comment]
yeah, think this can be closed
