### ISSUE TITLE
Spell:GetTimeSinceLastCast,Spell:GetLastCastTime()

### ISSUE THREAD

**Issue by JustRebeccabla** [abunai10/CaffeineIssues#21]
![image](https://github.com/abunai10/CaffeineIssues/assets/46432043/a5215efb-b825-4916-9c52-a38a8fe78fc7)

Both no bueno.

**Comment by abunai10** [comment]
The issue comes from the EventManager only tracking UNIT_SPELLCAST_SUCCEEDED for spells in the global spellbook.

I've added a check to ensure the spell is coming from the player before "GetSpell" and made it work for all spells now.

Will likely need to do something better than this in the future.

```lua
Caffeine.Globals.EventManager:RegisterWoWEvent("UNIT_SPELLCAST_SUCCEEDED", function(...)
    local unit, castGUID, spellID = ...

	if unit ~= "player" then return end

    local spell = Caffeine.Globals.SpellBook:GetSpell(spellID)

    if unit == "player" and spell then
        spell.lastCastAt = GetTime()

        if spell:GetPostCastFunction() then
            spell:GetPostCastFunction()(spell)
        end
    end
end)```

**Comment by Laksmack** [comment]
This is still an issue, tested on tinkr today
