### ISSUE TITLE
Commits sometimes are NOT pushed

### ISSUE THREAD

**Issue by JustRebeccabla** [abunai10/CaffeineIssues#24]
We had it happen now two times (that we noticed) yesterday that a commit that was live on github wasnt actively pushed to users even hours later until a new commit was done to the same file.

![image](https://github.com/abunai10/CaffeineIssues/assets/46432043/3d7e126f-7bf0-4b1f-a10b-348e9313e9b3)

Super concerning if we cant trust our commits to be live.

**Comment by Laksmack** [comment]
We need this looked at as a top priority - we had so many issues yesterday and pushed so many potential fixes - it was hard to tell what was live and what not.
We experienced delays (~20 mins)  and files not loading (forcepush to fix) and changes simply never making it all
