### ISSUE TITLE
SmartQueue does not respect that we are mounted

### ISSUE THREAD

**Issue by JustRebeccabla** [abunai10/CaffeineIssues#26]
Unlocker:  All
Expansion: Retail
OS: All
Client Language: All
Have Spells on your action bar that pages to the one you have for your dragonriding abilities.

And press the dragon ride ability on your bar.

It will try to cast the spell that was originally on your Action bar 

https://github.com/abunai10/CaffeineIssues/assets/46432043/6175b03c-710e-470a-ae14-f1c70bf11ae0

**Comment by abunai10** [comment]
Fixed in next update.
