### ISSUE TITLE
.25s missed every gcd

### ISSUE THREAD

**Issue by Hassliebe** [abunai10/CaffeineIssues#5]
Unlocker:  Daemonic
Expansion: Dragonflight
OS: Windows 10
Client Language: English
Explanation: Caffeine seems to miss .25s every single global, resulting in a fully missed gcd every 4-5 gcds spent depending on haste.
Relevant lua errors, if any: no lua errors but trying to attach GIF soon™
https://gifyu.com/image/S65OM

(not sure if relevant but including it anyways)
Module Name:  BM Hunter Angry Panda
Race: Tauren
Class: Hunter
Spec: BM
Level: 70

Steps to Reproduce: get a gcd tracker weak aura like https://wago.io/8_NEYlmc3 and see it happen 
Does issue persist after a /reload? yes
Does the issue persist after restarting your game client? yes
Screenshot of your File Structure: local loading on daemonic/windows
Addons List: happens with 0 addons (weak auras for tracking)

**Comment by abunai10** [comment]
This seems to be solved with the most recent variable tick rate update.
