### ISSUE TITLE
Actionbar throws LUA error on load 

### ISSUE THREAD

**Issue by Laksmack** [abunai10/CaffeineIssues#7]
154x FrameXML/ActionBar.lua:13: 'for' limit must be a number
[string "@FrameXML/ActionBar.lua"]:13: in function <FrameXML/ActionBar.lua:3>
[string "=[C]"]: in function `?'
[string "Luraph"]:39: in function `?'
[string "Luraph"]:39: in function <[string "Luraph"]:39>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "Luraph"]:39: in function `?'
[string "Luraph"]:39: in function `?'
[string "Luraph"]:39: in function `?'
[string "Luraph"]:39: in function `?'
[string "Luraph"]:39: in function <[string "Luraph"]:39>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "Evaluator:LoadEncBuffer"]:31: in function <[string "Evaluator:LoadEncBuffer"]:28>

**Comment by abunai10** [comment]
This is due to the current Hotbar on Dragonflight using a fake "Actionbar". It's something that can be fixed, but as it doesn't effect performance it is low priority.

**Comment by Laksmack** [comment]
as of Nov 1st, this bug is still present <nod>

**Comment by Laksmack** [comment]
I am not sure this bug is harmless.  The error is really large and could cause some clients to crash ... I think

**Comment by abunai10** [comment]
h8 u
